export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ORG_ADMIN = 'ORG_ADMIN',
  BRANCH_MANAGER = 'BRANCH_MANAGER',
  OPS_MANAGER = 'OPS_MANAGER',
  BOOKING_MANAGER = 'BOOKING_MANAGER',
  FLEET_MANAGER = 'FLEET_MANAGER',
  CREW_MANAGER = 'CREW_MANAGER',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
  CUSTOMER_SUPPORT = 'CUSTOMER_SUPPORT',
  CONCIERGE = 'CONCIERGE',
  CREW = 'CREW',
  CAPTAIN = 'CAPTAIN',
  MARINA_MANAGER = 'MARINA_MANAGER',
  MARINA_OPS = 'MARINA_OPS',
  DOCK_MANAGER = 'DOCK_MANAGER',
  CLUB_MANAGER = 'CLUB_MANAGER',
  SALES_MANAGER = 'SALES_MANAGER',
  SALES_REP = 'SALES_REP',
  CUSTOMER = 'CUSTOMER',
  MEMBER = 'MEMBER',
  YACHT_OWNER = 'YACHT_OWNER',
}

export enum BookingStatus {
  INQUIRY = 'INQUIRY',
  QUOTE = 'QUOTE',
  PENDING = 'PENDING',
  RESERVED = 'RESERVED',
  DEPOSIT_PAID = 'DEPOSIT_PAID',
  CONFIRMED = 'CONFIRMED',
  CONTRACT_PENDING = 'CONTRACT_PENDING',
  CONTRACT_SIGNED = 'CONTRACT_SIGNED',
  READY = 'READY',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  AUTHORIZED = 'AUTHORIZED',
  CAPTURED = 'CAPTURED',
  PAID = 'PAID',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  REFUNDED = 'REFUNDED',
  FAILED = 'FAILED',
}

export enum Currency {
  USD = 'USD',
  EUR = 'EUR',
  GBP = 'GBP',
  AED = 'AED',
  CAD = 'CAD',
  AUD = 'AUD',
  INR = 'INR',
  SGD = 'SGD',
  JPY = 'JPY',
}

export enum BusinessType {
  YACHT_CHARTER = 'YACHT_CHARTER',
  CHARTER_OPERATOR = 'CHARTER_OPERATOR',
  YACHT_OPERATOR = 'YACHT_OPERATOR',
  YACHT_BROKER = 'YACHT_BROKER',
  YACHT_CLUB = 'YACHT_CLUB',
  MARINA = 'MARINA',
  MARINA_AND_YACHT_CLUB = 'MARINA_AND_YACHT_CLUB',
  MANAGEMENT_COMPANY = 'MANAGEMENT_COMPANY',
  LUXURY_EVENT = 'LUXURY_EVENT',
  OTHER = 'OTHER',
}

export enum FleetSize {
  SINGLE_VESSEL = '1',
  SMALL_FLEET = '2_5',
  MEDIUM_FLEET = '6_15',
  LARGE_FLEET = '16_PLUS',
  SIZE_1_5 = 'SIZE_1_5',
  SIZE_6_20 = 'SIZE_6_20',
  SIZE_21_50 = 'SIZE_21_50',
  SIZE_51_100 = 'SIZE_51_100',
  SIZE_100_PLUS = 'SIZE_100_PLUS',
  SIZE_50_PLUS = 'SIZE_50_PLUS',
}

export enum YachtOperationalStatus {
  ACTIVE = 'ACTIVE',
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED',
  BOOKED = 'BOOKED',
  PREPARING = 'PREPARING',
  READY = 'READY',
  IN_CHARTER = 'IN_CHARTER',
  POST_CHARTER = 'POST_CHARTER',
  MAINTENANCE = 'MAINTENANCE',
  OUT_OF_SERVICE = 'OUT_OF_SERVICE',
  ARCHIVED = 'ARCHIVED',
}

export enum CrewRole {
  CAPTAIN = 'CAPTAIN',
  FIRST_OFFICER = 'FIRST_OFFICER',
  ENGINEER = 'ENGINEER',
  CHEF = 'CHEF',
  STEWARD = 'STEWARD',
  DECKHAND = 'DECKHAND',
  OTHER = 'OTHER',
}

export enum CrewStatus {
  AVAILABLE = 'AVAILABLE',
  ASSIGNED = 'ASSIGNED',
  ON_CHARTER = 'ON_CHARTER',
  UNAVAILABLE = 'UNAVAILABLE',
  ON_LEAVE = 'ON_LEAVE',
  INACTIVE = 'INACTIVE',
}

export enum CertStatus {
  VALID = 'VALID',
  EXPIRING_SOON = 'EXPIRING_SOON',
  EXPIRED = 'EXPIRED',
}

export enum MaintenanceStatus {
  REPORTED = 'REPORTED',
  PLANNED = 'PLANNED',
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  WAITING_PARTS = 'WAITING_PARTS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum MaintenancePriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum InspectionType {
  PRE_CHARTER = 'PRE_CHARTER',
  POST_CHARTER = 'POST_CHARTER',
  MAINTENANCE = 'MAINTENANCE',
  GENERAL = 'GENERAL',
}

export enum InspectionStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  PASSED = 'PASSED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum InspectionItemResult {
  PASS = 'PASS',
  FAIL = 'FAIL',
  NOT_CHECKED = 'NOT_CHECKED',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}

export enum ChecklistStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum ChecklistItemResult {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
}

export enum TaskStatus {
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum TaskPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum LeadStatus {
  NEW = 'NEW',
  CONTACTED = 'CONTACTED',
  QUALIFIED = 'QUALIFIED',
  DEMO_SCHEDULED = 'DEMO_SCHEDULED',
  PROPOSAL = 'PROPOSAL',
  NEGOTIATION = 'NEGOTIATION',
  WON = 'WON',
  CLOSED_WON = 'CLOSED_WON',
  LOST = 'LOST',
  CLOSED_LOST = 'CLOSED_LOST',
  NURTURE = 'NURTURE',
}

// Phase 3 IoT Enums
export enum DeviceType {
  GPS = 'GPS',
  ENGINE = 'ENGINE',
  FUEL = 'FUEL',
  BATTERY = 'BATTERY',
  BILGE = 'BILGE',
  TEMPERATURE = 'TEMPERATURE',
  WATER_LEVEL = 'WATER_LEVEL',
  OTHER = 'OTHER',
}

export enum DeviceStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  OFFLINE = 'OFFLINE',
  ERROR = 'ERROR',
  MAINTENANCE = 'MAINTENANCE',
}

export enum MetricType {
  SPEED = 'SPEED',
  HEADING = 'HEADING',
  LATITUDE = 'LATITUDE',
  LONGITUDE = 'LONGITUDE',
  FUEL_LEVEL = 'FUEL_LEVEL',
  BATTERY_VOLTAGE = 'BATTERY_VOLTAGE',
  BATTERY_CHARGE = 'BATTERY_CHARGE',
  ENGINE_RPM = 'ENGINE_RPM',
  ENGINE_TEMP = 'ENGINE_TEMP',
  ENGINE_HOURS = 'ENGINE_HOURS',
  BILGE_STATUS = 'BILGE_STATUS',
  TEMPERATURE = 'TEMPERATURE',
  WATER_LEVEL = 'WATER_LEVEL',
  CUSTOM = 'CUSTOM',
}

export enum TelemetryQuality {
  GOOD = 'GOOD',
  SUSPECT = 'SUSPECT',
  INVALID = 'INVALID',
}

export enum AlertSeverity {
  INFO = 'INFO',
  WARNING = 'WARNING',
  CRITICAL = 'CRITICAL',
}

export enum AlertCategory {
  DEVICE_OFFLINE = 'DEVICE_OFFLINE',
  HIGH_SPEED = 'HIGH_SPEED',
  LOW_BATTERY = 'LOW_BATTERY',
  LOW_FUEL = 'LOW_FUEL',
  HIGH_ENGINE_TEMPERATURE = 'HIGH_ENGINE_TEMPERATURE',
  BILGE_ALERT = 'BILGE_ALERT',
  GEOFENCE_EXIT = 'GEOFENCE_EXIT',
  GEOFENCE_ENTRY = 'GEOFENCE_ENTRY',
  ABNORMAL_READING = 'ABNORMAL_READING',
  OTHER = 'OTHER',
}

export enum AlertStatus {
  OPEN = 'OPEN',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  RESOLVED = 'RESOLVED',
  DISMISSED = 'DISMISSED',
}

export enum GeofenceShape {
  CIRCLE = 'CIRCLE',
  POLYGON = 'POLYGON',
}

export enum GeofenceEventType {
  ENTRY = 'ENTRY',
  EXIT = 'EXIT',
}

// Phase 4 Enums
export enum MarinaStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  UNDER_MAINTENANCE = 'UNDER_MAINTENANCE',
  CLOSED = 'CLOSED',
}

export enum DockStatus {
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED',
  MAINTENANCE = 'MAINTENANCE',
}

export enum BerthStatus {
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED',
  OCCUPIED = 'OCCUPIED',
  MAINTENANCE = 'MAINTENANCE',
  OUT_OF_SERVICE = 'OUT_OF_SERVICE',
}

export enum BerthReservationStatus {
  INQUIRY = 'INQUIRY',
  PENDING = 'PENDING',
  RESERVED = 'RESERVED',
  CONFIRMED = 'CONFIRMED',
  CHECK_IN = 'CHECK_IN',
  OCCUPIED = 'OCCUPIED',
  CHECK_OUT = 'CHECK_OUT',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum ContractType {
  SHORT_TERM = 'SHORT_TERM',
  LONG_TERM = 'LONG_TERM',
  SEASONAL = 'SEASONAL',
}

export enum ContractStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum ClubMemberStatus {
  ACTIVE = 'ACTIVE',
  PENDING = 'PENDING',
  SUSPENDED = 'SUSPENDED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum MembershipBillingCycle {
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  ANNUAL = 'ANNUAL',
}

export enum ClubEventStatus {
  UPCOMING = 'UPCOMING',
  ONGOING = 'ONGOING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

// Phase 5 Enums
export enum LeadSource {
  WEBSITE = 'WEBSITE',
  BOOKING_ENGINE = 'BOOKING_ENGINE',
  CONTACT_FORM = 'CONTACT_FORM',
  REFERRAL = 'REFERRAL',
  ADVERTISEMENT = 'ADVERTISEMENT',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  EMAIL = 'EMAIL',
  PHONE = 'PHONE',
  WHATSAPP = 'WHATSAPP',
  PARTNER = 'PARTNER',
  MANUAL = 'MANUAL',
  OTHER = 'OTHER',
}

export enum ActivityType {
  CALL = 'CALL',
  EMAIL = 'EMAIL',
  WHATSAPP = 'WHATSAPP',
  MEETING = 'MEETING',
  NOTE = 'NOTE',
  FOLLOW_UP = 'FOLLOW_UP',
  PROPOSAL = 'PROPOSAL',
  BOOKING = 'BOOKING',
  OTHER = 'OTHER',
}

export enum FollowUpStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  OVERDUE = 'OVERDUE',
}

export enum AutomationTrigger {
  LEAD_CREATED = 'LEAD_CREATED',
  LEAD_UPDATED = 'LEAD_UPDATED',
  BOOKING_CREATED = 'BOOKING_CREATED',
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  CHARTER_UPCOMING = 'CHARTER_UPCOMING',
  CHARTER_COMPLETED = 'CHARTER_COMPLETED',
  MAINTENANCE_COMPLETED = 'MAINTENANCE_COMPLETED',
  MEMBERSHIP_EXPIRING = 'MEMBERSHIP_EXPIRING',
  RESERVATION_CREATED = 'RESERVATION_CREATED',
  CUSTOMER_INACTIVE = 'CUSTOMER_INACTIVE',
}

export enum TemplateChannel {
  EMAIL = 'EMAIL',
  WHATSAPP = 'WHATSAPP',
  NOTIFICATION = 'NOTIFICATION',
}

export enum CampaignStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
}

// Phase 6 Enums
export enum CustomerBookingStatus {
  REQUESTED = 'REQUESTED',
  CONFIRMED = 'CONFIRMED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  READY = 'READY',
  UPCOMING = 'UPCOMING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum ServiceRequestStatus {
  REQUESTED = 'REQUESTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum ConciergeRequestStatus {
  REQUESTED = 'REQUESTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  PROPOSED = 'PROPOSED',
  ACCEPTED = 'ACCEPTED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum SupportTicketStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  WAITING_FOR_CUSTOMER = 'WAITING_FOR_CUSTOMER',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum SupportTicketPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum WaitlistStatus {
  WAITING = 'WAITING',
  NOTIFIED = 'NOTIFIED',
  CONVERTED = 'CONVERTED',
  CANCELLED = 'CANCELLED',
}

// Phase 7 Enterprise Enums
export enum SubscriptionPlan {
  STARTER = 'STARTER',
  PROFESSIONAL = 'PROFESSIONAL',
  BUSINESS = 'BUSINESS',
  ENTERPRISE = 'ENTERPRISE',
}

export enum SubscriptionStatus {
  TRIAL = 'TRIAL',
  ACTIVE = 'ACTIVE',
  PAST_DUE = 'PAST_DUE',
  SUSPENDED = 'SUSPENDED',
  CANCELLED = 'CANCELLED',
}

export enum TaxCategory {
  YACHT_CHARTER = 'YACHT_CHARTER',
  BERTH_LEASE = 'BERTH_LEASE',
  UTILITY_SERVICE = 'UTILITY_SERVICE',
  CLUB_MEMBERSHIP = 'CLUB_MEMBERSHIP',
  EVENT_TICKET = 'EVENT_TICKET',
}

export enum PrivacyRequestType {
  ACCESS = 'ACCESS',
  CORRECTION = 'CORRECTION',
  DELETION = 'DELETION',
  EXPORT = 'EXPORT',
}

export enum PrivacyRequestStatus {
  PENDING = 'PENDING',
  REVIEWING = 'REVIEWING',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
}

export enum SystemHealthStatus {
  HEALTHY = 'HEALTHY',
  WARNING = 'WARNING',
  DEGRADED = 'DEGRADED',
  DOWN = 'DOWN',
}

// Phase 8 Analytics Enums
export enum ForecastConfidence {
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
  INSUFFICIENT_DATA = 'INSUFFICIENT_DATA',
}

export enum MaintenanceRiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum CustomerSegment {
  VIP = 'VIP',
  HIGH_VALUE = 'HIGH_VALUE',
  REPEAT = 'REPEAT',
  AT_RISK = 'AT_RISK',
  INACTIVE = 'INACTIVE',
  NEW = 'NEW',
}

export enum ExecutiveAlertCategory {
  REVENUE = 'REVENUE',
  OCCUPANCY = 'OCCUPANCY',
  MAINTENANCE = 'MAINTENANCE',
  FLEET = 'FLEET',
  MARINA = 'MARINA',
  CRM = 'CRM',
  IOT = 'IOT',
}

export enum ExecutiveAlertSeverity {
  INFO = 'INFO',
  WARNING = 'WARNING',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}
